### ISSUE TITLE
Bitcode missing

### ISSUE THREAD

**Issue by odrobnik** [Temasys/SKYLINK-iOS#1]
Please enable Bitcode in your framework. At present if you are trying to build a project producing bit code the linker fails with this error:

> ld: > '/Users/oliver/Documents/Projects/Klickerr/Pods/SKYLINK/SKYLINK.framework/SKYLINK(libjingle_peerconnection_objc.RTCICECandidate.o)' does not contain bitcode. You must rebuild it with bit code > enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by RomainPln** [comment]
We do not support bit code, as stated in readme, we recommend to disable bit code for your target (set ENABLE_BITCODE = NO in your build settings)

**Comment by odrobnik** [comment]
@RomainPln Why? You should support it.

**Comment by RomainPln** [comment]
We use technologies not yet compatible.

**Comment by odrobnik** [comment]
Well, I am getting the error from `libjingle`, which was last updated 2011 ([changelog](https://developers.google.com/talk/libjingle/changelist))

You _will_ be having a problem when Apple starts requiring bit code for all iOS apps. They have already started doing that for tvOS apps for example.

**Comment by odrobnik** [comment]
@RomainPln so no comment, WHEN you will support bit code?

**Comment by waltermvp** [comment]
@odrobnik Did they start to require it yet or set a date for when it will be required? Im curious about this as well.

**Comment by lyx501135** [comment]
Theoretically we can support Bitcode now, we will discuss on it, thanks

**Comment by waltermvp** [comment]
@lyx501135 thanks for the update. Happy to help with testing or in any way I can.
