### ISSUE TITLE
Broadcast system support

### ISSUE THREAD

**Issue by iHamzaaK** [Temasys/SKYLINK-iOS#10]
Does this sdk supports broadcast system api that was released last year?

**Comment by lyx501135** [comment]
We are going to release it soon, thanks

**Comment by iHamzaaK** [comment]
Hi, 

Any update on this?

**Comment by lyx501135** [comment]
Hi thanks for your interest, you may try this demo first, https://testflight.apple.com/join/lvgrKW1Z
