### ISSUE TITLE
Crash trying to mute Audio/Video before a peer has joined

### ISSUE THREAD

**Issue by odrobnik** [Temasys/SKYLINK-iOS#3]
If you call `muteVideo` or `muteAudio` before a peer has joined the SDK causes the app to terminate with an NSInvalidArgumentException:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', 
reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: 
attempt to insert nil object from objects[1]'
```

**Comment by RomainPln** [comment]
Perhaps you were referring to the moment where the connection is not complete (not necessary before a peer joins).
This is fixed internally and next release will address that. Thanks for raising that up.
