### ISSUE TITLE
Audio Output

### ISSUE THREAD

**Issue by kenanchristian** [Temasys/SKYLINK-iOS#5]
I'm trying to do a one way video call, currently I'm only getting audio and video from the first person who join the room. A weird things happened though, the sound is coming through the earpiece not the speaker.

**Comment by RomainPln** [comment]
Hello, for the Audio output I suggest you look at the AppDelegate in our sample app. Please let us know if that helps.
Should I understand you also have trouble to establish media connection with more than 2 peers? If so, we would need steps to reproduce this behaviour in our sample app.
