### ISSUE TITLE
Version 1.0.11

### ISSUE THREAD

**Issue by danlniel** [Temasys/SKYLINK-iOS#7]
```
- (void)_handleMessage:(id)message
{
    SRFastLog(@"Received message");
    [self _performDelegateBlock:^{
        [self.delegate webSocket:self didReceiveMessage:message];
    }];
}

```
With the latest version, i always get error when try to call delegate
Thanks

**Comment by RomainPln** [comment]
Hello.
Thanks for this report. WE already are investigating this issue and will update with a fix ASAP.
Please also note latest version is 1.0.11.2 at the moment.
48 thanks.

**Comment by RomainPln** [comment]
Also, if you'd like to receive a pre-release to help us confirm the fix works for you please drop us an email at userhelp@temasys.com.sg

**Comment by danlniel** [comment]
Ok cool thanks,
Anyway sometimes didjoinpeer from SKYLINKConnectionRemotePeerDelegate is not called,
Is this because of server problem?

**Comment by RomainPln** [comment]
Hum, no, are you using Skylink Media Relay?

**Comment by danlniel** [comment]
Yea, this happen sometimes when you cant connect some period of time

**Comment by RomainPln** [comment]
Hello, for the original issue, could you try to do a pod update with the folowing in your podfile:
pod 'SKYLINK', :git => 'https://github.com/Temasys/SKYLINK-iOS.git', :branch => 'develop'

**Comment by RomainPln** [comment]
Hello @danlniel, I see you closed this issue, can i just confirm it means the version 1.0.11.2.1 on develop branch solves your issue ?

**Comment by danlniel** [comment]
Sory for late reply,
Yea Thanks a lot its working fine now.

**Comment by RomainPln** [comment]
Thanks.
